services:
  mysql:
    image: mysql:8
    container_name: salario-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payroll
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: salario-backend
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      DB_NAME: payroll
      JWT_SECRET: your-secret
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: salario-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  mysql-data:
